version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
    volumes:
      - appsettingsVolume:/app/appsettings.Development.json
      - dataVolume:/Data.db
  db:
    image: keinos/sqlite3

volumes:
  appsettingsVolume:
  dataVolume:
